### PR TITLE
Support scroll method.

### PR DESCRIPTION
**Pull request by kurnevsky**
Tested with `pasystray` - it changes volume on scroll.

### CODE REVIEW

**Review by colonelpanic8 — APPROVED** [review]
Cool! Don't we need something similar for "SecondaryActivate"

**Comment by colonelpanic8** [comment]
So basically it scrolls whatever your mouse has focus over? I'm not familiar with how gdk would process the scroll event.

**Comment by kurnevsky** [comment]
> Cool! Don't we need something similar for "SecondaryActivate"

Yes, but scroll event seemed to me simpler to implement, so I started with it :)

> So basically it scrolls whatever your mouse has focus over? I'm not familiar with how gdk would process the scroll event.

Yes.

**Comment by colonelpanic8** [comment]
> Yes, but scroll event seemed to me simpler to implement, so I started with it :)

Isn't it like the exact same thing pretty much? Just need to handle a different event, right?

**Comment by kurnevsky** [comment]
> Isn't it like the exact same thing pretty much? Just need to handle a different event, right?

Yes, but we already handle button press event. So likely we will need to check event type in that handler. And I'm not sure how it's handled now - in some cases it creates menu passed as parameter and in other cases it calls `IC.activate`. So I wonder if it needs to be changed somehow. Are there cases when we might want to call `IC.activate` if there is a menu?

**Pull request merged**
